sudo: required
services:
    - docker
    
before_install:
    - docker build -t meherbabu/docker-react-app -f Dockerfile.dev .

script:
    - docker run meherbabu/docker-react-app npm run test --coverage
    